### ISSUE TITLE
Can't run project (DEL)

### ISSUE THREAD

**Issue by skliarovartem** [nestjs-steroids/async-context#12]
I have "[Nest] 2170   - 10/03/2021, 3:12:22 PM   [ExceptionHandler] Async ID (8052) is not registered within internal cache."
error message during nest initialization.
What can be a reason?

**Comment by skliarovartem** [comment]
I found, this error I have when trying to get values in service constructor, like 
```
constructor(private readonly asyncContext: AsyncContext) 
{
       console.log(asyncContext.get("reqId"))
}
```
but when I use it in my methods it works ok.
Why it is not possible to get values in constructor? It will be very handy, to assign req id to logger just in one place, then in each method we need to retrieve some values like reqId
Many thanks!

**Comment by techvlad** [comment]
@skliarovartem 
Hello 👋
You need to call `this.asyncHook.register();` first
