### ISSUE TITLE
Can simultaneous request override traceId ?

### ISSUE THREAD

**Issue by TbotaPhantA** [nestjs-steroids/async-context#23]
If two users will send 2 requests simultaneously:
- first one will set `traceId: some-uuid-1`,
- second one will set `traceId: some-uuid-2`,

then:
- first one will log `some-uuid-2` (but it should log `some-uuid-1`, becuase this is first request)
- second one will log proper traceId `some-uuid-2`

Am I right or Am I wrong?

**Comment by techvlad** [comment]
No, if this corner case is possible - that's bug in Node.js core, see https://nodejs.org/api/async_context.html#class-asynclocalstorage
https://github.com/nodejs/node/issues/22360

**Comment by techvlad** [comment]
This library is simple wrapper for `AsyncLocalStorage`

**Comment by TbotaPhantA** [comment]
Got it, thank you😊!
